export module Meta.Predicate;

export import Meta.Predicate.Arithmetic;
export import Meta.Predicate.Pointer;
export import Meta.Predicate.Union;
export import Meta.Predicate.Fundamental;

// export import Meta.Predicate.Arithmetic;
// export import Meta.Predicate.Array;
// export import Meta.Predicate.BoundedArray;
// export import Meta.Predicate.Class;
// export import Meta.Predicate.Compound;
// export import Meta.Predicate.CompoundObject;
// export import Meta.Predicate.CompoundScalar;
// // export import Meta.Predicate.DerivedFrom;
// export import Meta.Predicate.Enum;
// export import Meta.Predicate.FloatingPoint;
// export import Meta.Predicate.Function;
// export import Meta.Predicate.Fundamental;
// export import Meta.Predicate.FundamentalScalar;
// export import Meta.Predicate.Integral;
// export import Meta.Predicate.LValueReference;
// export import Meta.Predicate.MemberPointer;
// export import Meta.Predicate.NullPointer;
// export import Meta.Predicate.Object;
// export import Meta.Predicate.Pointable;
// export import Meta.Predicate.Pointer;
// export import Meta.Predicate.Reference;
// export import Meta.Predicate.RValueReference;
// export import Meta.Predicate.Scalar;
// export import Meta.Predicate.ScopedEnum;
// export import Meta.Predicate.Signed;
// export import Meta.Predicate.SignedIntegral;
// export import Meta.Predicate.TypePack;
// export import Meta.Predicate.UnboundedArray;
// export import Meta.Predicate.Union;
// export import Meta.Predicate.UnscopedEnum;
// export import Meta.Predicate.Unsigned;
// export import Meta.Predicate.UserDefined;
// export import Meta.Predicate.ValuePack;
// export import Meta.Predicate.ValueTypePair;
// export import Meta.Predicate.Void;
