set(CMAKE_CXXModule_COMPILE_OPTIONS_EXPLICIT_LANGUAGE
    "-xc++-module"
)

set(CMAKE_CXXModule_FLAGS
    ${CMAKE_CXX_FLAGS}
)
set(CMAKE_CXXModule_SOURCE_FILE_EXTENSIONS
    .cpp
    .cppm
)
set(CMAKE_CXXModule_OUTPUT_EXTENSION
    .pcm
)
set(CMAKE_CXXModule_FLAGS
    ${CMAKE_CXX_FLAGS}
)
set(CMAKE_CXXModule_FLAGS_DEBUG
    "${CMAKE_CXX_FLAGS_DEBUG} ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}"
)
set(CMAKE_CXXModule_FLAGS_MINSIZEREL
    "${CMAKE_CXX_FLAGS_MINSIZEREL} ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}"
)
set(CMAKE_CXXModule_FLAGS_RELEASE
    "${CMAKE_CXX_FLAGS_RELEASE} ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}"
)
set(CMAKE_CXXModule_FLAGS_RELWITHDEBINFO
    "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}"
)

_cmake_common_language_platform_flags(
    CXXModule
)
set(CMAKE_CXXModule_COMPILE_OBJECT
    "<CMAKE_CXXModule_COMPILER> <DEFINES> <INCLUDES> <FLAGS> ${CMAKE_CXX_MODULE_BMI_ONLY_FLAG} <SOURCE> --output <OBJECT>"
)
set(CMAKE_CXXModule_INFORMATION_LOADED
    1
)
